### ISSUE TITLE
Add a menu

### ISSUE THREAD

**Issue by knoel99** [knoel99/knoel99.github.io#1]
The navigation menu should be:
Home
Objectif
Programme
Candidature
Tarifs
Débouchés
Contact

**Comment by mohamedchnafy-ds** [comment]
Mohamed Chnafy (mohamedchnafy-ds)

**Comment by CODgeass** [comment]
Placenticeras is the most famous ammonite in Canada, commonly known as 'Amolite'

**Comment by AIgbine** [comment]
AIgbine was here

**Comment by AbdrahamaneBerete** [comment]
AbdrahamaneBerete

**Comment by InesLAZREQ** [comment]
Inès LAZREQ (InesLAZREQ)

**Comment by JuaniSivo** [comment]
Bananas are 60% genetically similar to humans

**Comment by stephZambr** [comment]
stephZambr (stephZambr)

**Comment by abdulmalikajibadecodes** [comment]
Hello World!
