### ISSUE TITLE
Write a blog post of your choice: Big Data and Artificial Intelligence Analytics in Geosciences: Promises and Potential

### ISSUE THREAD

**Issue by knoel99** [knoel99/knoel99.github.io#10]
Write a blog post of your choice
Big Data and Artificial Intelligence Analytics in Geosciences: Promises and Potential
https://rock.geosociety.org/net/gsatoday/groundwork/G372GW/article.htm

**Comment by abdulmalikajibadecodes** [comment]
Hello there! I would love to take this project
